version: '2'
services:
  cocome:
    build:
      context: .
      dockerfile: dockerfile_cocome
    ports: 
      - "8080:8080"


  webshop:
    build:
      context: .
      dockerfile: dockerfile_webshop
    ports: 
      - "8580:8580"
    depends_on:
      - cocome
    links: 
      - cocome
  
    
